version: '2'

vars:
  BUILD: "build"
  BIN: "{{.BUILD}}/grpcntt{{exeExt}}"

tasks:

  default:
    cmds:
      - task: build

  generate:
    cmds:
      - "protoc --go_out=plugins=grpc:. rpc/service.proto"
    sources:
      - "rpc/*.proto"
    generates:
      - "rpc/*.go"

  clean:
    cmds:
      - "rm -vrf {{.BUILD}}"

  build:
    deps: [ generate ]
    cmds:
      - "go build -o {{.BIN}}"
    sources:
      - "*.go"
      - "**/*.go"
    generates:
      - "{{.BIN}}"
